/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionSheet: typeof import('./components/ActionSheet.vue')['default']
    AppShell: typeof import('./components/AppShell.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseToast: typeof import('./components/BaseToast.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    EventTimeline: typeof import('./components/EventTimeline.vue')['default']
    PageNav: typeof import('./components/PageNav.vue')['default']
    QuickDock: typeof import('./components/QuickDock.vue')['default']
    QuickRecordSheet: typeof import('./components/QuickRecordSheet.vue')['default']
    ReminderAlert: typeof import('./components/ReminderAlert.vue')['default']
    ReminderEditorSheet: typeof import('./components/ReminderEditorSheet.vue')['default']
    ResetHeader: typeof import('./components/ResetHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareCardSheet: typeof import('./components/ShareCardSheet.vue')['default']
    SummaryCards: typeof import('./components/SummaryCards.vue')['default']
    WeightSheet: typeof import('./components/WeightSheet.vue')['default']
    WheelPicker: typeof import('./components/WheelPicker.vue')['default']
  }
}
